ALTER TABLE users
ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50)
DEFAULT 'TENANT001';

ALTER TABLE warehouse
ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50)
DEFAULT 'TENANT001';

ALTER TABLE zone
ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50)
DEFAULT 'TENANT001';

ALTER TABLE rack
ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50)
DEFAULT 'TENANT001';

ALTER TABLE bin
ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50)
DEFAULT 'TENANT001';

ALTER TABLE inventory
ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50)
DEFAULT 'TENANT001';

ALTER TABLE warehouse_task
ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50)
DEFAULT 'TENANT001';

ALTER TABLE forklift
ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(50)
DEFAULT 'TENANT001';

