ALTER TABLE users
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE roles
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE roles
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE warehouse
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE warehouse
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE zone
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE zone
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE rack
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE rack
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE bin
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE bin
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE forklift
ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

ALTER TABLE forklift
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
