ALTER TABLE forklift
ADD COLUMN IF NOT EXISTS battery_level INTEGER;

ALTER TABLE forklift
ADD COLUMN IF NOT EXISTS speed NUMERIC(10,2);

ALTER TABLE forklift
ADD COLUMN IF NOT EXISTS heading NUMERIC(10,2);

ALTER TABLE forklift
ADD COLUMN IF NOT EXISTS last_seen TIMESTAMP;

ALTER TABLE forklift
ADD COLUMN IF NOT EXISTS telematics_source VARCHAR(100);
